### ISSUE TITLE
Gizmos in builds only working in the first scene

### ISSUE THREAD

**Issue by Zo0mey** [popcron/gizmos#10]
Hi, first of all, thanks for this awesome package, really useful in play mode.
I have one small issue.
When having more than one scenes. In the build, the gizmos are only rendering in the first scene. They just do not appear in the following scenes. Any thoughts?
Thanks for you help.
I'm using Unity 2019.1.0f2

**Comment by popcron** [comment]
Thanks for the report, this is likely fixed in the latest version, let me know if it for sure does.

**Comment by Zo0mey** [comment]
Thanks for your fast answer. It indeed works with the new Unity version (2019.1.4f1).
Thanks for your help, I'll close this issue now :)
