### ISSUE TITLE
Gizmo for VR

### ISSUE THREAD

**Issue by kirevdokimov** [popcron/gizmos#13]
I am working with standalone VR (Oculus Go, Oculus Quest) where I can only use builds to test things. This tool is great, but when this is in VR, where there is 3 cameras (left, right, center eyes) I cannot see gizmos things because everything is drawing to center camera. It would be great if this tool will be able to work with 2 cameras at the same time.

I just write this here to ask if you can make this feature or advice how to do so. Anyway I am going to figure out how it works and then try to make a solution.

Have a nice day :)

**Comment by kirevdokimov** [comment]
Ok, temporary solution is to remove camera constraint from `GizmosInstance.OnRendered(Camera camera);`
![image](https://user-images.githubusercontent.com/5202070/70918063-8713e080-202f-11ea-8d83-aa48f2cc9897.png)

**Comment by kirevdokimov** [comment]
As I understand the code below calculates queue to points once after something changed with queue, then it just skips (`if (!queue[e].active) continue;`) calculations for next cameras. Well that means there is no performance impact to use multiple cameras.

I made predicate function to resolve is the camera fits to be used with gizmo or not
https://github.com/Nobinator/gizmos/commit/36ab12db201c929686d919dd26c58e4085a35a83

Everything with my case is ok, but there is at least two controversial point:
#### First one
`Gizmos.Camera` is pointless for now because of unknown amount of cameras that fits to predicate. There is gizmo functions that depends on it, but in a very specific way. e.g `Circle` use camera just to get orientation, well, we can just pass Quaternion as a parameter here as we do in cases like Cube or Cone.
#### Second one
I dont know what to do with 
```
GeometryUtility.CalculateFrustumPlanes(camera, cameraPlanes);
if (GeometryUtility.TestPlanesAABB(cameraPlanes, bounds)){ ...
```
because `GizmosInstance.currentRenderingCamera` is not defined as single camera, but as many cameras at different time, so it is possible just to remove frustum clipping at all, but it is rough.

**Comment by popcron** [comment]
I dont have a VR setup so I cant verify if this works as expected in VR or not. Also, the reason why there is a filter, was to prevent the gizmos from renderering to useless cameras (UI camera, etc).

The Gizmos.Camera property could for sure be replaced with a static predicate to do manual filtering else where in game code.

As for the frustum calculation, this check is here to only render gizmos if theyre visibile, with the predicate replacement, this would have to be done for every camera, and only render the gizmo if any camera sees is.

**Comment by popcron** [comment]
Merged the pr, can you verify if it works for you?

Also reimplement the frustum culling so that it calculates per camera individually (and per eye as well). The `Gizmos.Camera` property was added back but marked as obsolete because it doesnt do anything anymore. 

The predicate filter with the scene camera being always present is a good idea, though I added the MainCamera as another default because this change would likely break existing projects that just rely on the MainCamera.

**Comment by kirevdokimov** [comment]
I can say everything works completely okay since PR approve :)
