### ISSUE TITLE
Some materials turns back to its original(pink) when project is reopened or sometime on scene reloading in Universal Rendering pipeline Unity 2019.3.0f6.

### ISSUE THREAD

**Issue by sohailzaheer** [popcron/gizmos#17]
Anyone else facing the same issue or I'm making the mistake??
It only for some materials other materials are perfectly fine, but some materials have to be converted every time when I reopen the project.

**Comment by popcron** [comment]
How exactly is this related to the gizmos package?

**Comment by sohailzaheer** [comment]
The problem solved, I extract the materials from the model and then convert it to URP, it works fine.
