### ISSUE TITLE
Prevent Drawing Over Worldspace and Transparent UI

### ISSUE THREAD

**Issue by Bit00009** [popcron/gizmos#25]
Hi @popcron, I just noticed gizmos are drawing over icons I use in my worldspace canvas.
Any suggestion or idea to fix it?

**Comment by popcron** [comment]
Not that I'm aware of, GL lines is going to draw over everything it seems no matter what

**Comment by Bit00009** [comment]
Well, How in editor itself 3d icons are getting draw over lines generated by gizmos?

**Comment by popcron** [comment]
Not sure

**Comment by Bit00009** [comment]
Here :
![vs](https://user-images.githubusercontent.com/65079764/104136163-bd926b00-53a9-11eb-8706-81b73106a1a0.png)

**Comment by popcron** [comment]
I believe that's because unity canvas ui isn't drawn the same way that scene gizmos are. Even if the canvas is marked as screen space, it is still rendering from world space into the camera

**Comment by Bit00009** [comment]
Do you mean unity editor viewport use a separate camera for the icons and add it after gizmos drawn?
[Also please check this](https://answers.unity.com/questions/21691/drawing-semi-transparent-objects-with-glbeginglqua.html)

I found this too [from here](https://forum.unity.com/threads/gl-lines-sorting-problem.529403/):
> If you can use a dynamic mesh with MeshTopology.Lines instead of GL.Lines, you can get proper transparency sorting.

**Comment by Bit00009** [comment]
Fixed it ;)

> GL lines is going to draw over everything it seems no matter what

Not true.

**Comment by popcron** [comment]
Glad you got it solved, gonna close this issue unless otherwise
