### ISSUE TITLE
"Authentication failed" error caused every time I pressed to play

### ISSUE THREAD

**Issue by Reguluz** [popcron/gizmos#26]
Sorry, me again.
Actually, it happened long time ago.
Every time I pressed to play in edit mode, this error caused. Because of it did not cause any other problem after I pressed to unpause, I didn't asked for help. For I need to test on play mode more frequently, now it puzzled me a lot.
How can I fix it? In fact, every scene whatever it has some script to use you plugin or not will cause this error as the same.
The error log is on below.

IOException: Authentication failed because the remote party has closed the transport stream.
Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status) (at <14e3453b740b4bd690e8d4e5a013a715>:0)
(wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus)
Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) (at <14e3453b740b4bd690e8d4e5a013a715>:0)
Mono.Net.Security.AsyncProtocolRequest+<ProcessOperation>d__24.MoveNext () (at <14e3453b740b4bd690e8d4e5a013a715>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () (at <fb001e01371b4adca20013e0ac763896>:0)
Mono.Net.Security.AsyncProtocolRequest+<StartOperation>d__23.MoveNext () (at <14e3453b740b4bd690e8d4e5a013a715>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
Mono.Net.Security.MobileAuthenticatedStream+<ProcessAuthentication>d__47.MoveNext () (at <14e3453b740b4bd690e8d4e5a013a715>:0)
Rethrow as AggregateException: One or more errors occurred.
System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.Tasks.Task.Wait () (at <fb001e01371b4adca20013e0ac763896>:0)
Mono.Net.Security.MobileAuthenticatedStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) (at <14e3453b740b4bd690e8d4e5a013a715>:0)
Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) (at <14e3453b740b4bd690e8d4e5a013a715>:0)
System.Net.WebConnection.CreateStream (System.Net.HttpWebRequest request) (at <14e3453b740b4bd690e8d4e5a013a715>:0)
Rethrow as WebException: Error: SecureChannelFailure (One or more errors occurred.)
System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) (at <14e3453b740b4bd690e8d4e5a013a715>:0)
System.Net.WebClient.GetWebResponse (System.Net.WebRequest request, System.IAsyncResult result) (at <14e3453b740b4bd690e8d4e5a013a715>:0)
System.Net.WebClient.DownloadBitsResponseCallback (System.IAsyncResult result) (at <14e3453b740b4bd690e8d4e5a013a715>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <fb001e01371b4adca20013e0ac763896>:0)
Updater+<IsUpdateAvailable>d__6.MoveNext () (at Library/PackageCache/com.popcron.gizmos@41dfa17124/Editor/Updater.cs:28)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <fb001e01371b4adca20013e0ac763896>:0)
Updater+<CheckForUpdates>d__8.MoveNext () (at Library/PackageCache/com.popcron.gizmos@41dfa17124/Editor/Updater.cs:71)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <fb001e01371b4adca20013e0ac763896>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <2791c1cdbfd943f6aba0f758c93ccc78>:0)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by popcron** [comment]
Oh that's the updater trying to update the package, but unity changed it to use a package lock json file and its not handled for that. This error doesn't get in the way of the api or gizmos so that can continue on its own.

**Comment by Reguluz** [comment]
> Oh that's the updater trying to update the package, but unity changed it to use a package lock json file and its not handled for that. This error doesn't get in the way of the api or gizmos so that can continue on its own.

Is there any way I can do to avoid this situation?

**Comment by popcron** [comment]
I will likely just remove the updater, so on your end, you can probably do the same until I update the package

**Comment by Reguluz** [comment]
ok, thanks
