### ISSUE TITLE
Material can't be changed through Gizmos

### ISSUE THREAD

**Issue by RunninglVlan** [popcron/gizmos#3]
```
//use custom material, if null it uses a default line material
Gizmos.Material = material;
```
This is an example from README which isn't working right now. I could change the material only this way: `Popcron.GizmosInstance.Material = material;`

**Comment by popcron** [comment]
Fixed.

**Comment by RunninglVlan** [comment]
BTW, do you know that it's possible to [close issues right from commit messages](https://help.github.com/en/articles/closing-issues-using-keywords)? Pretty handy feature!
